"""UI pages."""

from src.ui.pages.ab_page import build_ab_app, build_ab_page
from src.ui.pages.admin_page import build_admin_page, handle_admin_refresh, handle_upgrade_user
from src.ui.pages.auth_page import build_auth_page, handle_login, handle_register
from src.ui.pages.chat_page import build_chat_page
from src.ui.pages.chat_page import chat_course_title_from_scope, chat_course_title_text
from src.ui.pages.student_page import (
    build_student_page,
    handle_back_to_student,
    handle_logout,
    handle_open_ab_compare,
    handle_open_chat,
    handle_open_student_course,
    student_courses_update,
)
from src.ui.pages.student_course_page import (
    build_student_course_page,
    student_course_title_text,
)
from src.ui.pages.teacher_page import (
    build_teacher_page,
    handle_add_course,
    handle_open_responsible_course,
    handle_open_teacher_course,
    teacher_available_courses_update,
    teacher_name_text,
    teacher_responsible_courses_update,
)
from src.ui.pages.teacher_course_page import (
    build_teacher_course_page,
    handle_add_student,
    handle_confirm_enrollment,
    handle_import_students_csv,
    handle_course_instructions_input,
    handle_delete_material,
    handle_refresh_ingestion,
    handle_save_course_instructions,
    handle_start_ingestion,
    handle_upload_materials,
    handle_view_as_student,
    teacher_course_ingestion_status_text,
    teacher_course_instructions_updates,
    teacher_course_instructions_counter_update,
    teacher_course_instructions_input_update,
    teacher_course_instructions_status_update,
    teacher_course_material_choices_update,
    teacher_course_material_status_update,
    teacher_course_tabs_update,
    teacher_course_student_import_file_update,
    teacher_course_student_import_results_update,
    teacher_course_student_status_update,
    teacher_course_student_choices_update,
    teacher_course_students_text,
    teacher_course_title_text,
)

__all__ = [
    "build_ab_app",
    "build_ab_page",
    "build_admin_page",
    "build_auth_page",
    "build_chat_page",
    "chat_course_title_from_scope",
    "chat_course_title_text",
    "build_student_page",
    "build_student_course_page",
    "build_teacher_page",
    "build_teacher_course_page",
    "handle_admin_refresh",
    "handle_add_course",
    "handle_add_student",
    "handle_confirm_enrollment",
    "handle_import_students_csv",
    "handle_course_instructions_input",
    "handle_delete_material",
    "handle_refresh_ingestion",
    "handle_save_course_instructions",
    "handle_start_ingestion",
    "handle_upload_materials",
    "handle_back_to_student",
    "handle_login",
    "handle_logout",
    "handle_open_ab_compare",
    "handle_open_chat",
    "handle_open_responsible_course",
    "handle_open_student_course",
    "handle_open_teacher_course",
    "handle_register",
    "handle_upgrade_user",
    "handle_view_as_student",
    "teacher_course_ingestion_status_text",
    "teacher_course_instructions_updates",
    "teacher_course_instructions_counter_update",
    "teacher_course_instructions_input_update",
    "teacher_course_instructions_status_update",
    "teacher_course_material_choices_update",
    "teacher_course_material_status_update",
    "teacher_course_tabs_update",
    "teacher_course_student_import_file_update",
    "teacher_course_student_import_results_update",
    "teacher_course_student_status_update",
    "teacher_course_student_choices_update",
    "student_course_title_text",
    "student_courses_update",
    "teacher_course_students_text",
    "teacher_course_title_text",
    "teacher_available_courses_update",
    "teacher_name_text",
    "teacher_responsible_courses_update",
]
